import React from "react";
import Head from 'next/head'
import styles from '../styles/Home.module.css'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Peach</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="https://emojipedia-us.s3.dualstack.us-west-1.amazonaws.com/thumbs/240/apple/325/peach_1f351.png" />
      </Head>
      <script
          src="https://auth.magic.link/pnp/login"
          data-magic-publishable-api-key="pk_live_FAF905554D7C9B98"
          data-redirect-uri="/wallet">
        </script> 
    </div>
  )
}
